plus3it/join-domain-formula

join-domain/elx/pbis-config.sls, join-domain/elx/pbis.sls
- Sets user home dir param
- Sets user interactive shell param
- Ignores other domains in multi-domain forest
- Sets domain trust to only the explicitly-joined domain
=> PBIS configuration tasks

join-domain/elx/pbis-grpCfg.sls, pillar.example
Fixes #15 
* Updated `pillar.example` to add sample value
* Updated `pbis-grpCfg.sls` to add functionality for updating `/etc/ssh/sshd_config` file
=> Restricts SSH by group

join-domain/elx/files/pbis-clndir.sh, join-domain/elx/pbis.sls
Fixes #35 
New script will search target-domain for potential conflicts. If conflicts are found, script attempts resolution by trying to delete existing directory object. If object-deletion fails, rest of formula will fail.
=> Add Handler for Computer-Object Collisions in Target-Domain

join-domain/elx/pbis.sls, join-domain/windows/init.sls
Provides a mechanism through which users can easily set the `outpath` at which an instance should be placed when it joins the domain.
=> Use grain to override `oupath` from pillar

join-domain/elx/files/pbis-join.sh
* Null values in Pillar get passed as 'None', short-circuiting the
UNDEF logic used for setting appropriate TARGOU
* Change TARGOU logic's if statement to case to make multi-value
matching more compact
=> Change handling for "no OU" use-case

join-domain/windows/init.sls
This patch will use a new, "pending" computer name when joining a
Windows system to an Active Directory domain. This allows a user
to rename a computer, then join a domain, and the new computer
name will be used for the computer account. Without this patch,
the old computer name would be used for the domain computer account.
This flag has been tested to work even if the computer name is not
changing.
See https://msdn.microsoft.com/en-us/library/windows/desktop/aa370433(v=vs.85).aspx.
=> Join domain with new name

README.md, join-domain/windows/init.sls, join-domain/windows/map.jinja, pillar.example
Reads admins from pillar and from grains and generates a unique list of admins, all of which are added to the local administrator group.
Fixes #52
=> Supports adding domain users and groups as local admins

join-domain/windows/files/Invoke-ScriptDeleteTask.ps1, join-domain/windows/files/New-LocalGroupMember.ps1, join-domain/windows/files/Register-RunOnceStartupTask.ps1, join-domain/windows/init.sls, join-domain/windows/map.jinja
Adding local admins prior to this patch sometimes failed when the computer name had also changed, and when the system had just joined the domain but had not yet rebooted. The error message indicated that the trust relationship with the domain had failed. However, simply rebooting the system would repair the trust, and typically if the trust is broken then a reboot will not fix it. It is believed that some part of the authentication with the domain was continuing to use the old computer name, which caused the trust issues under the described circumstances.
This patch changes the mechanism for adding local admins, such that the members are added _after_ the system reboots. This is accomplished by registering a scheduled task that executes at system startup. The task runs a script that adds …
=> Uses a run-once startup task to add local admins

join-domain/elx/pbis/config.sls
Initial indications are that this fixes ordering without breaking anything further when used against production-environment's staging OU.
Need to get with original problem-reporter and verify that it fixes the issue seen in their environment/OU.
=> Initial fix/workaround for Issue #63

README.md, join-domain/elx/pbis/files/join.sh
*Note:* when integrating with PBIS on EL7, it will be necessary to ensure that PBIS is version 8.5 or greater (tested with 8.5.2) - older versions have issues parsing the EL7 krb5.conf file.
=> Fixes Issue 72

join-domain/elx/pbis/files/fix-collisions.sh, join-domain/elx/pbis/files/join.sh
Previously, the `PWdecrypt()` function was failing with a bad decrypt error, but was still returning bad data. The returned value wasn't being tested, so in fix-collisions.sh,  `CheckObject()` was still called. That function was also failing due to the bad password, in a way that caused `EXISTS` to be empty. `CheckObject()` then returned "NONE", which was matched as having no collisions, causing the script to report a stateful success. Salt would then continue to execute states that depended on fix-collisions.
This patch modifies `PWdecrypt()` to return an empty string if the decrypt fails. It then tests the return value and exits statefully with a failure if the returned value is empty. Salt then fails the dependent states without executing them.
=> Exits with stateful failure on a bad decryption

join-domain/elx/pbis/config.sls, join-domain/elx/pbis/files/fix-collisions.sh, join-domain/elx/pbis/files/join.sh, join-domain/elx/pbis/init.sls, join-domain/elx/pbis/map.jinja, pillar.example
* Install method works directly with RPMs, rather than SHAR
* Collision-test uses same command as the pbis install script to check whether the system is already domain-joined
=> Reworks elx pbis install and collision-test methods

join-domain/elx/pbis/config.sls
Disabling nss enumeration helps prevent lwsmd from locking up the
system when querying user info in a domain with a large number of
users and/or groups. Domain-based authentication still works fine.
=> Disables nss enumeration if it is enabled

.travis.yml, appveyor.yml, join-domain/elx/pbis/config.sls
The pbis config utility will return exit code 5 if the system
is not yet joined to the domain. The command still applies the
setting, so ignore this exit code.
=> Ignores invalid bad exit from pbis-config

join-domain/windows/files/Set-DnsSearchSuffix.ps1
Windows 2016 does not use the Ec2Config service, so the config.xml file is not present. It is not necessary to configure the equivalent SSM agent, since the SSM agent only sets the DNS search suffix at instance launch rather than every boot (as with the Ec2Config service). This patch tests for the file path before modifying it, meaning that on Windows 2016 this section is now just skipped.
Windows 2008 R2 comes with PowerShell 3.0, which does not include the commandlet `Set-DnsClientGlobalSetting`. This patch tests for the commandlet existence and if missing will fall back to the WMI method for setting the DNS search suffix.
=> Improves support of DnsSearchSuffix feature on ws2008r2 and ws2106

README.md, join-domain/windows/files/JoinDomain.ps1, join-domain/windows/init.sls, join-domain/windows/map.jinja, pillar.example, tests/docker/centos6/Dockerfile, tests/docker/centos7/Dockerfile
Allows users to tailor the retries to their environment. Large domains tend to take more time to sync the object deletion, which increases the wait time before the join will succeed.
=> Exposes retries option that can be user-controlled

join-domain/elx/pbis/config.sls, pillar.example
Obviated kludgery in the `join-domain.sh` (closes #100) and  `fix-collisions.sh` (closes #101)
=> Improve logic around additional domains to trust

.travis.yml, join-domain/elx/files/ssh-allow-group.sh, join-domain/elx/pbis/files/fix-collisions.sh, join-domain/elx/pbis/files/fix-hostname.sh, join-domain/elx/pbis/files/fix-pam.sh, join-domain/elx/pbis/files/install.sh, join-domain/elx/pbis/files/join.sh
Previously, if the query using `adtool` wholly failed (i.e., exited non-zero), the `fix-collision.sh` script would go about its merry way and attempt the nuke-action, any way. In some use-cases, if the `adtool`-based query exits non-zero, the nuke-action would also fail with a non-zero exit, causing subsequent actions (like the domain-join operation) to be wholly skipped. This modification should allow a domain-join to be attempted even if `adtool` is unusable (bug in PBIS version; incompatibility with domain security-settings, etc.)
closes #106 
** NOTE: Version of `adtool` in PBIS 8.5.3-293 is highly-broken (LDAP auth non-functional in many use-cases) : the `adtool` query-logic was failing but not being caught (due to missing error-logic). Will want to upgrade deployed PBIS version to …
=> Handle failures of adtool

join-domain/elx/pbis/config.sls
Closes #109 
Would have made this conditional, but making this the default value hasn't seemed to break PBIS capabilities with non-`LdapSignAndSeal` AD controllers.
=> Add `LdapSignAndSeal` to config tasks

join-domain/elx/pbis/init.sls, pillar.example
Extended the `pbis` init-file's contents to check pillar for a `pbis-ddns` flag (update `pillar.example`, too). If present and the value is `true`, the Linux join-domain formula will invoke the PBIS `udate-dns` utility to attempt a DDNS update. 
Unfortunately, lab DNS is not compatible. I will need to test this in the production dev account. I know the utility works there. However, I need to verify whether the fact that it gets a positive return on the A-record update but a negative return on the PTR-record update causes a non-zero exit state.
Closes #111
=> Conditionally-invoke PBIS's update-dns Utility

join-domain/elx/openldap-client/files/find-collisions.sh
- Ensure that sub-shells can resolve relevant var-vals under more use-conditions/contexts
- Ensures that the LDAP query is done for the shortname (if `hostname` returns FQDN)
- Makes script work with more-pedantic invocation-modes.
=> Export2 subshells

join-domain/elx/openldap-client/files/find-collisions.sh
Some vars that never get referenced in the test environment get triggered in one of the prod environments ...pissing off strict-mode. This fixes the ones that got activated today.
=> Ensure vars are properly initialized

join-domain/elx/openldap-client/files/find-collisions.sh, join-domain/elx/pbis/files/join.sh
- 9894b9c makes PBIS's `join.sh` output more verbose (closes #128 )
- 9f2b16a does similar for OpenLDAP's `find-collisions.sh`
=> Increase Scripts' Verbosity

README.md, join-domain/elx/openldap-client/files/find-collisions.sh, join-domain/elx/openldap-client/find-collision.sls, join-domain/elx/openldap-client/map.jinja, join-domain/elx/pbis/files/join.sh, pillar.example
With this change, when the domain collision-fixer script (`find-collisions.sh`) is run, it will attempt to restrict the list of domain-controllers consulted based on the value set via the `ad_site_name` key-value set in pillar:
~~~
ADstuff-2019-09-13-21:29:09.debug.log:2019-09-13 21:29:13,953 [salt.state:1976][INFO][29015] Completed state [find-collisions.sh -d "test.aws.lab" -s "<SITE_NAME>" -u "<JOIN_USER>" -c "<CRYPT_STRING>" -k "<CRYPT_KEY>" --mode saltstack] at time 21:29:13.953038 (duration_in_ms=301.656)
~~~
...whereas, if no such key-value is set, no restriction attempt is made.
~~~
ADstuff-2019-09-13-21:29:44.debug.log:2019-09-13 21:29:48,834 [salt.state:1976][INFO][29369] Completed state [find-collisions.sh -d "test.aws.lab" -u "<JOIN_USER>" -c "<CRYPT_STRING>" -k "<CRYPT_KEY>" …
=> Add support for Active Directory Sites

.travis.yml, README.md
Changes:
*  Added sample script to verify encrypted password Windows
*  Switch to single quotes in sample Linux bash command to handle special characters.
=> Updates README to provide additional guidance on encrypted password process

join-domain/elx/pbis/files/fix-hostname.sh
The quoting in the BASEIP logic is flawed and generates an error:
```
>               "$(ip addr show "${DEFIF}" | \
>                 awk '/inet /{print $2}' | \
>                 sed -e 's#/.*$##' -e 's/\./ /g' \
>               )")
-bash: printf: 10 0 5 99: invalid number
```
Moving the quotes to surround the entire command, including the printf, fixes the issue:
```
0A000563
```
=> Fixes BASEIP logic so command works and keeps shellcheck happy

join-domain/windows/files/JoinDomain.ps1
I *think* this test was keeping this function from removing a found
computer object. At one point in time, that was fine, as the Add-Computer
commandlet would go ahead and replace or reuse it, if needed. However, on
domain controllers with a reasonably current set of patches, that is not
allowed. It will fail with errors and a log similar to the below, in
%windir%\debug\netsetup.log.
```
NetpCheckForDomainSIDCollision: returning 0x0(0).
NetpGetComputerObjectDn: Cracking DNS domain name ..../ into Netbios on \\....
NetpGetComputerObjectDn: Crack results:         name = ....\
NetpGetComputerObjectDn: Cracking account name ....$ on \\....
NetpGetComputerObjectDn: Crack results:         (Account already exists) DN = CN=....
NetpGetADObjectOwnerAttributes: Looking up attributes for machine …
```
=> Removes windows computer object if found, unconditionally

join-domain/elx/openldap-client/files/find-collisions.sh, join-domain/elx/openldap-client/find-collision.sls, join-domain/elx/openldap-client/map.jinja, pillar.example
Refactored. The server-suitability testing is now three phases:
1. Generate a list of candidate-servers from a DNS lookup
2. Do a port-ping of those servers to validate which ones are _reachable_ &ndash; remove from the suitable servers list any that aren't port-reachable 
3. Do a TLS validation-check &ndash; removing any that fail from the suitable servers list (defaults to "on" but can be disabled by explicitly setting the `CHK_TLS_SPT` env-var to `false`)
Closes #187
=> Update to attempt LDAP+TLS If available

join-domain/elx/init.sls, join-domain/elx/openldap-client/files/find-collisions.sh, join-domain/elx/openldap-client/find-collision.sls, join-domain/elx/openldap-client/map.jinja, join-domain/elx/sssd/init.sls, pillar.example
This PR:
1. Changes how the `openldap-client` is `include`d in the join-domain workflow: instead of being called at the top-level (the `elx` layer), it is called by the `sssd` layer. This allows proper handling of error-exits from the `ldapsearch`  and `ldapdelete` operations
2. Allows error-exits from the `ldapsearch`  and `ldapdelete` operations to be either fatal or non-fatal to the overall `join-domain` workflow (set via `lldap_fatal_exit` pillar-variable).
Closes #190
=> Better integrates the openldap-client module with the sssd module

join-domain/elx/sssd/init.sls
Per the Red Hat [documentation](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/9/html/considerations_in_adopting_rhel_9/assembly_identity-management_considerations-in-adopting-rhel-9#known-issues-identity-management_assembly_identity-management), in order to support AD-based authentication via the `realm` service, RHEL 9's FIPS-posture must be relaxed by executing:
```bash
update-crypto-policies --set FIPS:AD-SUPPORT
```
This PR adds this logic as a prep-step prior to attempting to execute `realm join …` on RHEL 9 (and higher) ELx distros. 
Closes #218
=> Add conditional FIPS Posture-Relaxation Handler
